name: fluboard
description: Calendar board built with Flutter

publish_to: 'none'
version: 0.0.2-dev+2

environment:
  sdk: ">=2.17.6 <3.0.5"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl:
  syncfusion_flutter_calendar: ^20.2.40
  window_manager: ^0.2.5
  http: ^0.13.5
  get_it: ^7.2.0
  provider: ^6.0.3
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - .env