name: fluboard
description: Calendar board built with Flutter

publish_to: 'none'
version: 0.0.2-dev+2

environment:
  sdk: ">=2.17.6 <3.0.5"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl:
  syncfusion_flutter_calendar: ^20.2.43
  window_manager: ^0.2.5
  http: ^0.13.5
  get_it: ^7.2.0
  provider: ^6.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
#  firebase_auth: ^3.6.3
#  firebase_core: ^1.20.1
  googleapis: ^9.1.0
  googleapis_auth: ^1.3.1
  url_launcher: ^6.0.18
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  build_runner: ^2.2.0

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - .env